// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/member.proto

package memberpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type MembershipType int32

const (
	MembershipType_MEMBERSHIP_TYPE_UNSPECIFIED MembershipType = 0
	MembershipType_MEMBERSHIP_TYPE_REGULAR     MembershipType = 1
	MembershipType_MEMBERSHIP_TYPE_VIP         MembershipType = 2
	MembershipType_MEMBERSHIP_TYPE_CORPORATE   MembershipType = 3
	MembershipType_MEMBERSHIP_TYPE_STUDENT     MembershipType = 4
	MembershipType_MEMBERSHIP_TYPE_SENIOR      MembershipType = 5
)

// Enum value maps for MembershipType.
var (
	MembershipType_name = map[int32]string{
		0: "MEMBERSHIP_TYPE_UNSPECIFIED",
		1: "MEMBERSHIP_TYPE_REGULAR",
		2: "MEMBERSHIP_TYPE_VIP",
		3: "MEMBERSHIP_TYPE_CORPORATE",
		4: "MEMBERSHIP_TYPE_STUDENT",
		5: "MEMBERSHIP_TYPE_SENIOR",
	}
	MembershipType_value = map[string]int32{
		"MEMBERSHIP_TYPE_UNSPECIFIED": 0,
		"MEMBERSHIP_TYPE_REGULAR":     1,
		"MEMBERSHIP_TYPE_VIP":         2,
		"MEMBERSHIP_TYPE_CORPORATE":   3,
		"MEMBERSHIP_TYPE_STUDENT":     4,
		"MEMBERSHIP_TYPE_SENIOR":      5,
	}
)

func (x MembershipType) Enum() *MembershipType {
	p := new(MembershipType)
	*p = x
	return p
}

func (x MembershipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MembershipType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_member_proto_enumTypes[0].Descriptor()
}

func (MembershipType) Type() protoreflect.EnumType {
	return &file_proto_member_proto_enumTypes[0]
}

func (x MembershipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MembershipType.Descriptor instead.
func (MembershipType) EnumDescriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{0}
}

type MemberStatus int32

const (
	MemberStatus_MEMBER_STATUS_UNSPECIFIED MemberStatus = 0
	MemberStatus_MEMBER_STATUS_ACTIVE      MemberStatus = 1
	MemberStatus_MEMBER_STATUS_SUSPENDED   MemberStatus = 2
	MemberStatus_MEMBER_STATUS_EXPIRED     MemberStatus = 3
	MemberStatus_MEMBER_STATUS_PENDING     MemberStatus = 4
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNSPECIFIED",
		1: "MEMBER_STATUS_ACTIVE",
		2: "MEMBER_STATUS_SUSPENDED",
		3: "MEMBER_STATUS_EXPIRED",
		4: "MEMBER_STATUS_PENDING",
	}
	MemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNSPECIFIED": 0,
		"MEMBER_STATUS_ACTIVE":      1,
		"MEMBER_STATUS_SUSPENDED":   2,
		"MEMBER_STATUS_EXPIRED":     3,
		"MEMBER_STATUS_PENDING":     4,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_member_proto_enumTypes[1].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_proto_member_proto_enumTypes[1]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{1}
}

// Core types
type Member struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClubId             uint32                 `protobuf:"varint,2,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	UserId             uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberNumber       string                 `protobuf:"bytes,4,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	MembershipType     MembershipType         `protobuf:"varint,5,opt,name=membership_type,json=membershipType,proto3,enum=reciprocal_clubs.member.v1.MembershipType" json:"membership_type,omitempty"`
	Status             MemberStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=reciprocal_clubs.member.v1.MemberStatus" json:"status,omitempty"`
	BlockchainIdentity string                 `protobuf:"bytes,7,opt,name=blockchain_identity,json=blockchainIdentity,proto3" json:"blockchain_identity,omitempty"`
	Profile            *MemberProfile         `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	JoinedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *Member) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Member) GetMemberNumber() string {
	if x != nil {
		return x.MemberNumber
	}
	return ""
}

func (x *Member) GetMembershipType() MembershipType {
	if x != nil {
		return x.MembershipType
	}
	return MembershipType_MEMBERSHIP_TYPE_UNSPECIFIED
}

func (x *Member) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *Member) GetBlockchainIdentity() string {
	if x != nil {
		return x.BlockchainIdentity
	}
	return ""
}

func (x *Member) GetProfile() *MemberProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Member) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Member) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Member) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MemberProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address          *Address               `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	EmergencyContact *EmergencyContact      `protobuf:"bytes,7,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	Preferences      *MemberPreferences     `protobuf:"bytes,8,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberProfile) Reset() {
	*x = MemberProfile{}
	mi := &file_proto_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberProfile) ProtoMessage() {}

func (x *MemberProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberProfile.ProtoReflect.Descriptor instead.
func (*MemberProfile) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MemberProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MemberProfile) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *MemberProfile) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MemberProfile) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MemberProfile) GetEmergencyContact() *EmergencyContact {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *MemberProfile) GetPreferences() *MemberPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *MemberProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemberProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type EmergencyContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Relationship  string                 `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyContact) Reset() {
	*x = EmergencyContact{}
	mi := &file_proto_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyContact) ProtoMessage() {}

func (x *EmergencyContact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyContact.ProtoReflect.Descriptor instead.
func (*EmergencyContact) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{3}
}

func (x *EmergencyContact) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmergencyContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergencyContact) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *EmergencyContact) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *EmergencyContact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MemberPreferences struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmailNotifications bool                   `protobuf:"varint,2,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	SmsNotifications   bool                   `protobuf:"varint,3,opt,name=sms_notifications,json=smsNotifications,proto3" json:"sms_notifications,omitempty"`
	PushNotifications  bool                   `protobuf:"varint,4,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	MarketingEmails    bool                   `protobuf:"varint,5,opt,name=marketing_emails,json=marketingEmails,proto3" json:"marketing_emails,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MemberPreferences) Reset() {
	*x = MemberPreferences{}
	mi := &file_proto_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPreferences) ProtoMessage() {}

func (x *MemberPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPreferences.ProtoReflect.Descriptor instead.
func (*MemberPreferences) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{4}
}

func (x *MemberPreferences) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberPreferences) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *MemberPreferences) GetSmsNotifications() bool {
	if x != nil {
		return x.SmsNotifications
	}
	return false
}

func (x *MemberPreferences) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *MemberPreferences) GetMarketingEmails() bool {
	if x != nil {
		return x.MarketingEmails
	}
	return false
}

// CreateMember
type CreateMemberRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	ClubId         uint32                      `protobuf:"varint,1,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	UserId         uint32                      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MembershipType MembershipType              `protobuf:"varint,3,opt,name=membership_type,json=membershipType,proto3,enum=reciprocal_clubs.member.v1.MembershipType" json:"membership_type,omitempty"`
	Profile        *CreateMemberProfileRequest `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_proto_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMemberRequest) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *CreateMemberRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMemberRequest) GetMembershipType() MembershipType {
	if x != nil {
		return x.MembershipType
	}
	return MembershipType_MEMBERSHIP_TYPE_UNSPECIFIED
}

func (x *CreateMemberRequest) GetProfile() *CreateMemberProfileRequest {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CreateMemberProfileRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	FirstName        string                         `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                         `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth      *timestamppb.Timestamp         `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PhoneNumber      string                         `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address          *CreateAddressRequest          `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	EmergencyContact *CreateEmergencyContactRequest `protobuf:"bytes,6,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	Preferences      *CreatePreferencesRequest      `protobuf:"bytes,7,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMemberProfileRequest) Reset() {
	*x = CreateMemberProfileRequest{}
	mi := &file_proto_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberProfileRequest) ProtoMessage() {}

func (x *CreateMemberProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMemberProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateMemberProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateMemberProfileRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *CreateMemberProfileRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateMemberProfileRequest) GetAddress() *CreateAddressRequest {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateMemberProfileRequest) GetEmergencyContact() *CreateEmergencyContactRequest {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *CreateMemberProfileRequest) GetPreferences() *CreatePreferencesRequest {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateEmergencyContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Relationship  string                 `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmergencyContactRequest) Reset() {
	*x = CreateEmergencyContactRequest{}
	mi := &file_proto_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmergencyContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmergencyContactRequest) ProtoMessage() {}

func (x *CreateEmergencyContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmergencyContactRequest.ProtoReflect.Descriptor instead.
func (*CreateEmergencyContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEmergencyContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmergencyContactRequest) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *CreateEmergencyContactRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateEmergencyContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreatePreferencesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EmailNotifications bool                   `protobuf:"varint,1,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	SmsNotifications   bool                   `protobuf:"varint,2,opt,name=sms_notifications,json=smsNotifications,proto3" json:"sms_notifications,omitempty"`
	PushNotifications  bool                   `protobuf:"varint,3,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	MarketingEmails    bool                   `protobuf:"varint,4,opt,name=marketing_emails,json=marketingEmails,proto3" json:"marketing_emails,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreatePreferencesRequest) Reset() {
	*x = CreatePreferencesRequest{}
	mi := &file_proto_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePreferencesRequest) ProtoMessage() {}

func (x *CreatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*CreatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePreferencesRequest) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *CreatePreferencesRequest) GetSmsNotifications() bool {
	if x != nil {
		return x.SmsNotifications
	}
	return false
}

func (x *CreatePreferencesRequest) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *CreatePreferencesRequest) GetMarketingEmails() bool {
	if x != nil {
		return x.MarketingEmails
	}
	return false
}

type CreateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberResponse) Reset() {
	*x = CreateMemberResponse{}
	mi := &file_proto_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberResponse) ProtoMessage() {}

func (x *CreateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberResponse.ProtoReflect.Descriptor instead.
func (*CreateMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// GetMember
type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_proto_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{11}
}

func (x *GetMemberRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type GetMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberResponse) Reset() {
	*x = GetMemberResponse{}
	mi := &file_proto_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberResponse) ProtoMessage() {}

func (x *GetMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberResponse.ProtoReflect.Descriptor instead.
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{12}
}

func (x *GetMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// GetMemberByUserID
type GetMemberByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberByUserIDRequest) Reset() {
	*x = GetMemberByUserIDRequest{}
	mi := &file_proto_member_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberByUserIDRequest) ProtoMessage() {}

func (x *GetMemberByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetMemberByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{13}
}

func (x *GetMemberByUserIDRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetMemberByMemberNumber
type GetMemberByMemberNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberNumber  string                 `protobuf:"bytes,1,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberByMemberNumberRequest) Reset() {
	*x = GetMemberByMemberNumberRequest{}
	mi := &file_proto_member_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberByMemberNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberByMemberNumberRequest) ProtoMessage() {}

func (x *GetMemberByMemberNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberByMemberNumberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberByMemberNumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{14}
}

func (x *GetMemberByMemberNumberRequest) GetMemberNumber() string {
	if x != nil {
		return x.MemberNumber
	}
	return ""
}

// GetMembersByClub
type GetMembersByClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClubId        uint32                 `protobuf:"varint,1,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersByClubRequest) Reset() {
	*x = GetMembersByClubRequest{}
	mi := &file_proto_member_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersByClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersByClubRequest) ProtoMessage() {}

func (x *GetMembersByClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersByClubRequest.ProtoReflect.Descriptor instead.
func (*GetMembersByClubRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{15}
}

func (x *GetMembersByClubRequest) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *GetMembersByClubRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMembersByClubRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMembersByClubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersByClubResponse) Reset() {
	*x = GetMembersByClubResponse{}
	mi := &file_proto_member_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersByClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersByClubResponse) ProtoMessage() {}

func (x *GetMembersByClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersByClubResponse.ProtoReflect.Descriptor instead.
func (*GetMembersByClubResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{16}
}

func (x *GetMembersByClubResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetMembersByClubResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateMemberProfile
type UpdateMemberProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Profile       *UpdateProfileRequest  `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberProfileRequest) Reset() {
	*x = UpdateMemberProfileRequest{}
	mi := &file_proto_member_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberProfileRequest) ProtoMessage() {}

func (x *UpdateMemberProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMemberProfileRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateMemberProfileRequest) GetProfile() *UpdateProfileRequest {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	FirstName        *string                        `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName         *string                        `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	DateOfBirth      *timestamppb.Timestamp         `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	PhoneNumber      *string                        `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Address          *CreateAddressRequest          `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	EmergencyContact *CreateEmergencyContactRequest `protobuf:"bytes,6,opt,name=emergency_contact,json=emergencyContact,proto3,oneof" json:"emergency_contact,omitempty"`
	Preferences      *CreatePreferencesRequest      `protobuf:"bytes,7,opt,name=preferences,proto3,oneof" json:"preferences,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_member_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateProfileRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateProfileRequest) GetAddress() *CreateAddressRequest {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateProfileRequest) GetEmergencyContact() *CreateEmergencyContactRequest {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *UpdateProfileRequest) GetPreferences() *CreatePreferencesRequest {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateMemberProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberProfileResponse) Reset() {
	*x = UpdateMemberProfileResponse{}
	mi := &file_proto_member_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberProfileResponse) ProtoMessage() {}

func (x *UpdateMemberProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMemberProfileResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// SuspendMember
type SuspendMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendMemberRequest) Reset() {
	*x = SuspendMemberRequest{}
	mi := &file_proto_member_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendMemberRequest) ProtoMessage() {}

func (x *SuspendMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendMemberRequest.ProtoReflect.Descriptor instead.
func (*SuspendMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{20}
}

func (x *SuspendMemberRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *SuspendMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SuspendMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendMemberResponse) Reset() {
	*x = SuspendMemberResponse{}
	mi := &file_proto_member_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendMemberResponse) ProtoMessage() {}

func (x *SuspendMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendMemberResponse.ProtoReflect.Descriptor instead.
func (*SuspendMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{21}
}

func (x *SuspendMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// ReactivateMember
type ReactivateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactivateMemberRequest) Reset() {
	*x = ReactivateMemberRequest{}
	mi := &file_proto_member_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactivateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactivateMemberRequest) ProtoMessage() {}

func (x *ReactivateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactivateMemberRequest.ProtoReflect.Descriptor instead.
func (*ReactivateMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{22}
}

func (x *ReactivateMemberRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type ReactivateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactivateMemberResponse) Reset() {
	*x = ReactivateMemberResponse{}
	mi := &file_proto_member_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactivateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactivateMemberResponse) ProtoMessage() {}

func (x *ReactivateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactivateMemberResponse.ProtoReflect.Descriptor instead.
func (*ReactivateMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{23}
}

func (x *ReactivateMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// DeleteMember
type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_proto_member_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteMemberRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

// ValidateMemberAccess
type ValidateMemberAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMemberAccessRequest) Reset() {
	*x = ValidateMemberAccessRequest{}
	mi := &file_proto_member_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberAccessRequest) ProtoMessage() {}

func (x *ValidateMemberAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateMemberAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{25}
}

func (x *ValidateMemberAccessRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type ValidateMemberAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanAccess     bool                   `protobuf:"varint,1,opt,name=can_access,json=canAccess,proto3" json:"can_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMemberAccessResponse) Reset() {
	*x = ValidateMemberAccessResponse{}
	mi := &file_proto_member_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberAccessResponse) ProtoMessage() {}

func (x *ValidateMemberAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateMemberAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{26}
}

func (x *ValidateMemberAccessResponse) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

// CheckMembershipStatus
type CheckMembershipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipStatusRequest) Reset() {
	*x = CheckMembershipStatusRequest{}
	mi := &file_proto_member_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipStatusRequest) ProtoMessage() {}

func (x *CheckMembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckMembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{27}
}

func (x *CheckMembershipStatusRequest) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type CheckMembershipStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *MembershipStatusInfo  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipStatusResponse) Reset() {
	*x = CheckMembershipStatusResponse{}
	mi := &file_proto_member_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipStatusResponse) ProtoMessage() {}

func (x *CheckMembershipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckMembershipStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{28}
}

func (x *CheckMembershipStatusResponse) GetStatus() *MembershipStatusInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

type MembershipStatusInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Status         MemberStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=reciprocal_clubs.member.v1.MemberStatus" json:"status,omitempty"`
	MembershipType MembershipType         `protobuf:"varint,3,opt,name=membership_type,json=membershipType,proto3,enum=reciprocal_clubs.member.v1.MembershipType" json:"membership_type,omitempty"`
	CanAccess      bool                   `protobuf:"varint,4,opt,name=can_access,json=canAccess,proto3" json:"can_access,omitempty"`
	JoinedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MembershipStatusInfo) Reset() {
	*x = MembershipStatusInfo{}
	mi := &file_proto_member_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusInfo) ProtoMessage() {}

func (x *MembershipStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusInfo.ProtoReflect.Descriptor instead.
func (*MembershipStatusInfo) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{29}
}

func (x *MembershipStatusInfo) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *MembershipStatusInfo) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *MembershipStatusInfo) GetMembershipType() MembershipType {
	if x != nil {
		return x.MembershipType
	}
	return MembershipType_MEMBERSHIP_TYPE_UNSPECIFIED
}

func (x *MembershipStatusInfo) GetCanAccess() bool {
	if x != nil {
		return x.CanAccess
	}
	return false
}

func (x *MembershipStatusInfo) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *MembershipStatusInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// GetMemberAnalytics
type GetMemberAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClubId        uint32                 `protobuf:"varint,1,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberAnalyticsRequest) Reset() {
	*x = GetMemberAnalyticsRequest{}
	mi := &file_proto_member_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberAnalyticsRequest) ProtoMessage() {}

func (x *GetMemberAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetMemberAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{30}
}

func (x *GetMemberAnalyticsRequest) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

type GetMemberAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *MemberAnalytics       `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberAnalyticsResponse) Reset() {
	*x = GetMemberAnalyticsResponse{}
	mi := &file_proto_member_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberAnalyticsResponse) ProtoMessage() {}

func (x *GetMemberAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetMemberAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{31}
}

func (x *GetMemberAnalyticsResponse) GetAnalytics() *MemberAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type MemberAnalytics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalMembers           int64                  `protobuf:"varint,1,opt,name=total_members,json=totalMembers,proto3" json:"total_members,omitempty"`
	ActiveMembers          int64                  `protobuf:"varint,2,opt,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"`
	NewMembersThisMonth    int64                  `protobuf:"varint,3,opt,name=new_members_this_month,json=newMembersThisMonth,proto3" json:"new_members_this_month,omitempty"`
	MembershipDistribution []*MembershipTypeCount `protobuf:"bytes,4,rep,name=membership_distribution,json=membershipDistribution,proto3" json:"membership_distribution,omitempty"`
	StatusDistribution     []*MemberStatusCount   `protobuf:"bytes,5,rep,name=status_distribution,json=statusDistribution,proto3" json:"status_distribution,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MemberAnalytics) Reset() {
	*x = MemberAnalytics{}
	mi := &file_proto_member_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberAnalytics) ProtoMessage() {}

func (x *MemberAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberAnalytics.ProtoReflect.Descriptor instead.
func (*MemberAnalytics) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{32}
}

func (x *MemberAnalytics) GetTotalMembers() int64 {
	if x != nil {
		return x.TotalMembers
	}
	return 0
}

func (x *MemberAnalytics) GetActiveMembers() int64 {
	if x != nil {
		return x.ActiveMembers
	}
	return 0
}

func (x *MemberAnalytics) GetNewMembersThisMonth() int64 {
	if x != nil {
		return x.NewMembersThisMonth
	}
	return 0
}

func (x *MemberAnalytics) GetMembershipDistribution() []*MembershipTypeCount {
	if x != nil {
		return x.MembershipDistribution
	}
	return nil
}

func (x *MemberAnalytics) GetStatusDistribution() []*MemberStatusCount {
	if x != nil {
		return x.StatusDistribution
	}
	return nil
}

type MembershipTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MembershipType         `protobuf:"varint,1,opt,name=type,proto3,enum=reciprocal_clubs.member.v1.MembershipType" json:"type,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipTypeCount) Reset() {
	*x = MembershipTypeCount{}
	mi := &file_proto_member_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipTypeCount) ProtoMessage() {}

func (x *MembershipTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipTypeCount.ProtoReflect.Descriptor instead.
func (*MembershipTypeCount) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{33}
}

func (x *MembershipTypeCount) GetType() MembershipType {
	if x != nil {
		return x.Type
	}
	return MembershipType_MEMBERSHIP_TYPE_UNSPECIFIED
}

func (x *MembershipTypeCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MemberStatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MemberStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=reciprocal_clubs.member.v1.MemberStatus" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberStatusCount) Reset() {
	*x = MemberStatusCount{}
	mi := &file_proto_member_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberStatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberStatusCount) ProtoMessage() {}

func (x *MemberStatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberStatusCount.ProtoReflect.Descriptor instead.
func (*MemberStatusCount) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{34}
}

func (x *MemberStatusCount) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *MemberStatusCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// HealthCheck
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_member_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{35}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_member_proto protoreflect.FileDescriptor

const file_proto_member_proto_rawDesc = "" +
	"\n" +
	"\x12proto/member.proto\x12\x1areciprocal_clubs.member.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xab\x04\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\aclub_id\x18\x02 \x01(\rR\x06clubId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12#\n" +
	"\rmember_number\x18\x04 \x01(\tR\fmemberNumber\x12S\n" +
	"\x0fmembership_type\x18\x05 \x01(\x0e2*.reciprocal_clubs.member.v1.MembershipTypeR\x0emembershipType\x12@\n" +
	"\x06status\x18\x06 \x01(\x0e2(.reciprocal_clubs.member.v1.MemberStatusR\x06status\x12/\n" +
	"\x13blockchain_identity\x18\a \x01(\tR\x12blockchainIdentity\x12C\n" +
	"\aprofile\x18\b \x01(\v2).reciprocal_clubs.member.v1.MemberProfileR\aprofile\x127\n" +
	"\tjoined_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x04\n" +
	"\rMemberProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12=\n" +
	"\aaddress\x18\x06 \x01(\v2#.reciprocal_clubs.member.v1.AddressR\aaddress\x12Y\n" +
	"\x11emergency_contact\x18\a \x01(\v2,.reciprocal_clubs.member.v1.EmergencyContactR\x10emergencyContact\x12O\n" +
	"\vpreferences\x18\b \x01(\v2-.reciprocal_clubs.member.v1.MemberPreferencesR\vpreferences\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x96\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"\x93\x01\n" +
	"\x10EmergencyContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\frelationship\x18\x03 \x01(\tR\frelationship\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\xdb\x01\n" +
	"\x11MemberPreferences\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12/\n" +
	"\x13email_notifications\x18\x02 \x01(\bR\x12emailNotifications\x12+\n" +
	"\x11sms_notifications\x18\x03 \x01(\bR\x10smsNotifications\x12-\n" +
	"\x12push_notifications\x18\x04 \x01(\bR\x11pushNotifications\x12)\n" +
	"\x10marketing_emails\x18\x05 \x01(\bR\x0fmarketingEmails\"\xee\x01\n" +
	"\x13CreateMemberRequest\x12\x17\n" +
	"\aclub_id\x18\x01 \x01(\rR\x06clubId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12S\n" +
	"\x0fmembership_type\x18\x03 \x01(\x0e2*.reciprocal_clubs.member.v1.MembershipTypeR\x0emembershipType\x12P\n" +
	"\aprofile\x18\x04 \x01(\v26.reciprocal_clubs.member.v1.CreateMemberProfileRequestR\aprofile\"\xc7\x03\n" +
	"\x1aCreateMemberProfileRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12J\n" +
	"\aaddress\x18\x05 \x01(\v20.reciprocal_clubs.member.v1.CreateAddressRequestR\aaddress\x12f\n" +
	"\x11emergency_contact\x18\x06 \x01(\v29.reciprocal_clubs.member.v1.CreateEmergencyContactRequestR\x10emergencyContact\x12V\n" +
	"\vpreferences\x18\a \x01(\v24.reciprocal_clubs.member.v1.CreatePreferencesRequestR\vpreferences\"\x93\x01\n" +
	"\x14CreateAddressRequest\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\x90\x01\n" +
	"\x1dCreateEmergencyContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\frelationship\x18\x02 \x01(\tR\frelationship\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xd2\x01\n" +
	"\x18CreatePreferencesRequest\x12/\n" +
	"\x13email_notifications\x18\x01 \x01(\bR\x12emailNotifications\x12+\n" +
	"\x11sms_notifications\x18\x02 \x01(\bR\x10smsNotifications\x12-\n" +
	"\x12push_notifications\x18\x03 \x01(\bR\x11pushNotifications\x12)\n" +
	"\x10marketing_emails\x18\x04 \x01(\bR\x0fmarketingEmails\"R\n" +
	"\x14CreateMemberResponse\x12:\n" +
	"\x06member\x18\x01 \x01(\v2\".reciprocal_clubs.member.v1.MemberR\x06member\"/\n" +
	"\x10GetMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\"O\n" +
	"\x11GetMemberResponse\x12:\n" +
	"\x06member\x18\x01 \x01(\v2\".reciprocal_clubs.member.v1.MemberR\x06member\"3\n" +
	"\x18GetMemberByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"E\n" +
	"\x1eGetMemberByMemberNumberRequest\x12#\n" +
	"\rmember_number\x18\x01 \x01(\tR\fmemberNumber\"`\n" +
	"\x17GetMembersByClubRequest\x12\x17\n" +
	"\aclub_id\x18\x01 \x01(\rR\x06clubId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"y\n" +
	"\x18GetMembersByClubResponse\x12<\n" +
	"\amembers\x18\x01 \x03(\v2\".reciprocal_clubs.member.v1.MemberR\amembers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x85\x01\n" +
	"\x1aUpdateMemberProfileRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\x12J\n" +
	"\aprofile\x18\x02 \x01(\v20.reciprocal_clubs.member.v1.UpdateProfileRequestR\aprofile\"\xd6\x04\n" +
	"\x14UpdateProfileRequest\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x01R\blastName\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vdateOfBirth\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x04 \x01(\tH\x03R\vphoneNumber\x88\x01\x01\x12O\n" +
	"\aaddress\x18\x05 \x01(\v20.reciprocal_clubs.member.v1.CreateAddressRequestH\x04R\aaddress\x88\x01\x01\x12k\n" +
	"\x11emergency_contact\x18\x06 \x01(\v29.reciprocal_clubs.member.v1.CreateEmergencyContactRequestH\x05R\x10emergencyContact\x88\x01\x01\x12[\n" +
	"\vpreferences\x18\a \x01(\v24.reciprocal_clubs.member.v1.CreatePreferencesRequestH\x06R\vpreferences\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x10\n" +
	"\x0e_date_of_birthB\x0f\n" +
	"\r_phone_numberB\n" +
	"\n" +
	"\b_addressB\x14\n" +
	"\x12_emergency_contactB\x0e\n" +
	"\f_preferences\"Y\n" +
	"\x1bUpdateMemberProfileResponse\x12:\n" +
	"\x06member\x18\x01 \x01(\v2\".reciprocal_clubs.member.v1.MemberR\x06member\"K\n" +
	"\x14SuspendMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"S\n" +
	"\x15SuspendMemberResponse\x12:\n" +
	"\x06member\x18\x01 \x01(\v2\".reciprocal_clubs.member.v1.MemberR\x06member\"6\n" +
	"\x17ReactivateMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\"V\n" +
	"\x18ReactivateMemberResponse\x12:\n" +
	"\x06member\x18\x01 \x01(\v2\".reciprocal_clubs.member.v1.MemberR\x06member\"2\n" +
	"\x13DeleteMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\":\n" +
	"\x1bValidateMemberAccessRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\"=\n" +
	"\x1cValidateMemberAccessResponse\x12\x1d\n" +
	"\n" +
	"can_access\x18\x01 \x01(\bR\tcanAccess\";\n" +
	"\x1cCheckMembershipStatusRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\"i\n" +
	"\x1dCheckMembershipStatusResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\v20.reciprocal_clubs.member.v1.MembershipStatusInfoR\x06status\"\xdd\x02\n" +
	"\x14MembershipStatusInfo\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\rR\bmemberId\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.reciprocal_clubs.member.v1.MemberStatusR\x06status\x12S\n" +
	"\x0fmembership_type\x18\x03 \x01(\x0e2*.reciprocal_clubs.member.v1.MembershipTypeR\x0emembershipType\x12\x1d\n" +
	"\n" +
	"can_access\x18\x04 \x01(\bR\tcanAccess\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"4\n" +
	"\x19GetMemberAnalyticsRequest\x12\x17\n" +
	"\aclub_id\x18\x01 \x01(\rR\x06clubId\"g\n" +
	"\x1aGetMemberAnalyticsResponse\x12I\n" +
	"\tanalytics\x18\x01 \x01(\v2+.reciprocal_clubs.member.v1.MemberAnalyticsR\tanalytics\"\xdc\x02\n" +
	"\x0fMemberAnalytics\x12#\n" +
	"\rtotal_members\x18\x01 \x01(\x03R\ftotalMembers\x12%\n" +
	"\x0eactive_members\x18\x02 \x01(\x03R\ractiveMembers\x123\n" +
	"\x16new_members_this_month\x18\x03 \x01(\x03R\x13newMembersThisMonth\x12h\n" +
	"\x17membership_distribution\x18\x04 \x03(\v2/.reciprocal_clubs.member.v1.MembershipTypeCountR\x16membershipDistribution\x12^\n" +
	"\x13status_distribution\x18\x05 \x03(\v2-.reciprocal_clubs.member.v1.MemberStatusCountR\x12statusDistribution\"k\n" +
	"\x13MembershipTypeCount\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.reciprocal_clubs.member.v1.MembershipTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"k\n" +
	"\x11MemberStatusCount\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.reciprocal_clubs.member.v1.MemberStatusR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*\xbf\x01\n" +
	"\x0eMembershipType\x12\x1f\n" +
	"\x1bMEMBERSHIP_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MEMBERSHIP_TYPE_REGULAR\x10\x01\x12\x17\n" +
	"\x13MEMBERSHIP_TYPE_VIP\x10\x02\x12\x1d\n" +
	"\x19MEMBERSHIP_TYPE_CORPORATE\x10\x03\x12\x1b\n" +
	"\x17MEMBERSHIP_TYPE_STUDENT\x10\x04\x12\x1a\n" +
	"\x16MEMBERSHIP_TYPE_SENIOR\x10\x05*\x9a\x01\n" +
	"\fMemberStatus\x12\x1d\n" +
	"\x19MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MEMBER_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17MEMBER_STATUS_SUSPENDED\x10\x02\x12\x19\n" +
	"\x15MEMBER_STATUS_EXPIRED\x10\x03\x12\x19\n" +
	"\x15MEMBER_STATUS_PENDING\x10\x042\xbc\f\n" +
	"\rMemberService\x12q\n" +
	"\fCreateMember\x12/.reciprocal_clubs.member.v1.CreateMemberRequest\x1a0.reciprocal_clubs.member.v1.CreateMemberResponse\x12h\n" +
	"\tGetMember\x12,.reciprocal_clubs.member.v1.GetMemberRequest\x1a-.reciprocal_clubs.member.v1.GetMemberResponse\x12x\n" +
	"\x11GetMemberByUserID\x124.reciprocal_clubs.member.v1.GetMemberByUserIDRequest\x1a-.reciprocal_clubs.member.v1.GetMemberResponse\x12\x84\x01\n" +
	"\x17GetMemberByMemberNumber\x12:.reciprocal_clubs.member.v1.GetMemberByMemberNumberRequest\x1a-.reciprocal_clubs.member.v1.GetMemberResponse\x12}\n" +
	"\x10GetMembersByClub\x123.reciprocal_clubs.member.v1.GetMembersByClubRequest\x1a4.reciprocal_clubs.member.v1.GetMembersByClubResponse\x12\x86\x01\n" +
	"\x13UpdateMemberProfile\x126.reciprocal_clubs.member.v1.UpdateMemberProfileRequest\x1a7.reciprocal_clubs.member.v1.UpdateMemberProfileResponse\x12t\n" +
	"\rSuspendMember\x120.reciprocal_clubs.member.v1.SuspendMemberRequest\x1a1.reciprocal_clubs.member.v1.SuspendMemberResponse\x12}\n" +
	"\x10ReactivateMember\x123.reciprocal_clubs.member.v1.ReactivateMemberRequest\x1a4.reciprocal_clubs.member.v1.ReactivateMemberResponse\x12W\n" +
	"\fDeleteMember\x12/.reciprocal_clubs.member.v1.DeleteMemberRequest\x1a\x16.google.protobuf.Empty\x12\x89\x01\n" +
	"\x14ValidateMemberAccess\x127.reciprocal_clubs.member.v1.ValidateMemberAccessRequest\x1a8.reciprocal_clubs.member.v1.ValidateMemberAccessResponse\x12\x8c\x01\n" +
	"\x15CheckMembershipStatus\x128.reciprocal_clubs.member.v1.CheckMembershipStatusRequest\x1a9.reciprocal_clubs.member.v1.CheckMembershipStatusResponse\x12\x83\x01\n" +
	"\x12GetMemberAnalytics\x125.reciprocal_clubs.member.v1.GetMemberAnalyticsRequest\x1a6.reciprocal_clubs.member.v1.GetMemberAnalyticsResponse\x12V\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a/.reciprocal_clubs.member.v1.HealthCheckResponseBAZ?reciprocal-clubs-backend/services/member-service/proto/memberpbb\x06proto3"

var (
	file_proto_member_proto_rawDescOnce sync.Once
	file_proto_member_proto_rawDescData []byte
)

func file_proto_member_proto_rawDescGZIP() []byte {
	file_proto_member_proto_rawDescOnce.Do(func() {
		file_proto_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_member_proto_rawDesc), len(file_proto_member_proto_rawDesc)))
	})
	return file_proto_member_proto_rawDescData
}

var file_proto_member_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_member_proto_goTypes = []any{
	(MembershipType)(0),                    // 0: reciprocal_clubs.member.v1.MembershipType
	(MemberStatus)(0),                      // 1: reciprocal_clubs.member.v1.MemberStatus
	(*Member)(nil),                         // 2: reciprocal_clubs.member.v1.Member
	(*MemberProfile)(nil),                  // 3: reciprocal_clubs.member.v1.MemberProfile
	(*Address)(nil),                        // 4: reciprocal_clubs.member.v1.Address
	(*EmergencyContact)(nil),               // 5: reciprocal_clubs.member.v1.EmergencyContact
	(*MemberPreferences)(nil),              // 6: reciprocal_clubs.member.v1.MemberPreferences
	(*CreateMemberRequest)(nil),            // 7: reciprocal_clubs.member.v1.CreateMemberRequest
	(*CreateMemberProfileRequest)(nil),     // 8: reciprocal_clubs.member.v1.CreateMemberProfileRequest
	(*CreateAddressRequest)(nil),           // 9: reciprocal_clubs.member.v1.CreateAddressRequest
	(*CreateEmergencyContactRequest)(nil),  // 10: reciprocal_clubs.member.v1.CreateEmergencyContactRequest
	(*CreatePreferencesRequest)(nil),       // 11: reciprocal_clubs.member.v1.CreatePreferencesRequest
	(*CreateMemberResponse)(nil),           // 12: reciprocal_clubs.member.v1.CreateMemberResponse
	(*GetMemberRequest)(nil),               // 13: reciprocal_clubs.member.v1.GetMemberRequest
	(*GetMemberResponse)(nil),              // 14: reciprocal_clubs.member.v1.GetMemberResponse
	(*GetMemberByUserIDRequest)(nil),       // 15: reciprocal_clubs.member.v1.GetMemberByUserIDRequest
	(*GetMemberByMemberNumberRequest)(nil), // 16: reciprocal_clubs.member.v1.GetMemberByMemberNumberRequest
	(*GetMembersByClubRequest)(nil),        // 17: reciprocal_clubs.member.v1.GetMembersByClubRequest
	(*GetMembersByClubResponse)(nil),       // 18: reciprocal_clubs.member.v1.GetMembersByClubResponse
	(*UpdateMemberProfileRequest)(nil),     // 19: reciprocal_clubs.member.v1.UpdateMemberProfileRequest
	(*UpdateProfileRequest)(nil),           // 20: reciprocal_clubs.member.v1.UpdateProfileRequest
	(*UpdateMemberProfileResponse)(nil),    // 21: reciprocal_clubs.member.v1.UpdateMemberProfileResponse
	(*SuspendMemberRequest)(nil),           // 22: reciprocal_clubs.member.v1.SuspendMemberRequest
	(*SuspendMemberResponse)(nil),          // 23: reciprocal_clubs.member.v1.SuspendMemberResponse
	(*ReactivateMemberRequest)(nil),        // 24: reciprocal_clubs.member.v1.ReactivateMemberRequest
	(*ReactivateMemberResponse)(nil),       // 25: reciprocal_clubs.member.v1.ReactivateMemberResponse
	(*DeleteMemberRequest)(nil),            // 26: reciprocal_clubs.member.v1.DeleteMemberRequest
	(*ValidateMemberAccessRequest)(nil),    // 27: reciprocal_clubs.member.v1.ValidateMemberAccessRequest
	(*ValidateMemberAccessResponse)(nil),   // 28: reciprocal_clubs.member.v1.ValidateMemberAccessResponse
	(*CheckMembershipStatusRequest)(nil),   // 29: reciprocal_clubs.member.v1.CheckMembershipStatusRequest
	(*CheckMembershipStatusResponse)(nil),  // 30: reciprocal_clubs.member.v1.CheckMembershipStatusResponse
	(*MembershipStatusInfo)(nil),           // 31: reciprocal_clubs.member.v1.MembershipStatusInfo
	(*GetMemberAnalyticsRequest)(nil),      // 32: reciprocal_clubs.member.v1.GetMemberAnalyticsRequest
	(*GetMemberAnalyticsResponse)(nil),     // 33: reciprocal_clubs.member.v1.GetMemberAnalyticsResponse
	(*MemberAnalytics)(nil),                // 34: reciprocal_clubs.member.v1.MemberAnalytics
	(*MembershipTypeCount)(nil),            // 35: reciprocal_clubs.member.v1.MembershipTypeCount
	(*MemberStatusCount)(nil),              // 36: reciprocal_clubs.member.v1.MemberStatusCount
	(*HealthCheckResponse)(nil),            // 37: reciprocal_clubs.member.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),          // 38: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 39: google.protobuf.Empty
}
var file_proto_member_proto_depIdxs = []int32{
	0,  // 0: reciprocal_clubs.member.v1.Member.membership_type:type_name -> reciprocal_clubs.member.v1.MembershipType
	1,  // 1: reciprocal_clubs.member.v1.Member.status:type_name -> reciprocal_clubs.member.v1.MemberStatus
	3,  // 2: reciprocal_clubs.member.v1.Member.profile:type_name -> reciprocal_clubs.member.v1.MemberProfile
	38, // 3: reciprocal_clubs.member.v1.Member.joined_at:type_name -> google.protobuf.Timestamp
	38, // 4: reciprocal_clubs.member.v1.Member.created_at:type_name -> google.protobuf.Timestamp
	38, // 5: reciprocal_clubs.member.v1.Member.updated_at:type_name -> google.protobuf.Timestamp
	38, // 6: reciprocal_clubs.member.v1.MemberProfile.date_of_birth:type_name -> google.protobuf.Timestamp
	4,  // 7: reciprocal_clubs.member.v1.MemberProfile.address:type_name -> reciprocal_clubs.member.v1.Address
	5,  // 8: reciprocal_clubs.member.v1.MemberProfile.emergency_contact:type_name -> reciprocal_clubs.member.v1.EmergencyContact
	6,  // 9: reciprocal_clubs.member.v1.MemberProfile.preferences:type_name -> reciprocal_clubs.member.v1.MemberPreferences
	38, // 10: reciprocal_clubs.member.v1.MemberProfile.created_at:type_name -> google.protobuf.Timestamp
	38, // 11: reciprocal_clubs.member.v1.MemberProfile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: reciprocal_clubs.member.v1.CreateMemberRequest.membership_type:type_name -> reciprocal_clubs.member.v1.MembershipType
	8,  // 13: reciprocal_clubs.member.v1.CreateMemberRequest.profile:type_name -> reciprocal_clubs.member.v1.CreateMemberProfileRequest
	38, // 14: reciprocal_clubs.member.v1.CreateMemberProfileRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	9,  // 15: reciprocal_clubs.member.v1.CreateMemberProfileRequest.address:type_name -> reciprocal_clubs.member.v1.CreateAddressRequest
	10, // 16: reciprocal_clubs.member.v1.CreateMemberProfileRequest.emergency_contact:type_name -> reciprocal_clubs.member.v1.CreateEmergencyContactRequest
	11, // 17: reciprocal_clubs.member.v1.CreateMemberProfileRequest.preferences:type_name -> reciprocal_clubs.member.v1.CreatePreferencesRequest
	2,  // 18: reciprocal_clubs.member.v1.CreateMemberResponse.member:type_name -> reciprocal_clubs.member.v1.Member
	2,  // 19: reciprocal_clubs.member.v1.GetMemberResponse.member:type_name -> reciprocal_clubs.member.v1.Member
	2,  // 20: reciprocal_clubs.member.v1.GetMembersByClubResponse.members:type_name -> reciprocal_clubs.member.v1.Member
	20, // 21: reciprocal_clubs.member.v1.UpdateMemberProfileRequest.profile:type_name -> reciprocal_clubs.member.v1.UpdateProfileRequest
	38, // 22: reciprocal_clubs.member.v1.UpdateProfileRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	9,  // 23: reciprocal_clubs.member.v1.UpdateProfileRequest.address:type_name -> reciprocal_clubs.member.v1.CreateAddressRequest
	10, // 24: reciprocal_clubs.member.v1.UpdateProfileRequest.emergency_contact:type_name -> reciprocal_clubs.member.v1.CreateEmergencyContactRequest
	11, // 25: reciprocal_clubs.member.v1.UpdateProfileRequest.preferences:type_name -> reciprocal_clubs.member.v1.CreatePreferencesRequest
	2,  // 26: reciprocal_clubs.member.v1.UpdateMemberProfileResponse.member:type_name -> reciprocal_clubs.member.v1.Member
	2,  // 27: reciprocal_clubs.member.v1.SuspendMemberResponse.member:type_name -> reciprocal_clubs.member.v1.Member
	2,  // 28: reciprocal_clubs.member.v1.ReactivateMemberResponse.member:type_name -> reciprocal_clubs.member.v1.Member
	31, // 29: reciprocal_clubs.member.v1.CheckMembershipStatusResponse.status:type_name -> reciprocal_clubs.member.v1.MembershipStatusInfo
	1,  // 30: reciprocal_clubs.member.v1.MembershipStatusInfo.status:type_name -> reciprocal_clubs.member.v1.MemberStatus
	0,  // 31: reciprocal_clubs.member.v1.MembershipStatusInfo.membership_type:type_name -> reciprocal_clubs.member.v1.MembershipType
	38, // 32: reciprocal_clubs.member.v1.MembershipStatusInfo.joined_at:type_name -> google.protobuf.Timestamp
	38, // 33: reciprocal_clubs.member.v1.MembershipStatusInfo.expires_at:type_name -> google.protobuf.Timestamp
	34, // 34: reciprocal_clubs.member.v1.GetMemberAnalyticsResponse.analytics:type_name -> reciprocal_clubs.member.v1.MemberAnalytics
	35, // 35: reciprocal_clubs.member.v1.MemberAnalytics.membership_distribution:type_name -> reciprocal_clubs.member.v1.MembershipTypeCount
	36, // 36: reciprocal_clubs.member.v1.MemberAnalytics.status_distribution:type_name -> reciprocal_clubs.member.v1.MemberStatusCount
	0,  // 37: reciprocal_clubs.member.v1.MembershipTypeCount.type:type_name -> reciprocal_clubs.member.v1.MembershipType
	1,  // 38: reciprocal_clubs.member.v1.MemberStatusCount.status:type_name -> reciprocal_clubs.member.v1.MemberStatus
	7,  // 39: reciprocal_clubs.member.v1.MemberService.CreateMember:input_type -> reciprocal_clubs.member.v1.CreateMemberRequest
	13, // 40: reciprocal_clubs.member.v1.MemberService.GetMember:input_type -> reciprocal_clubs.member.v1.GetMemberRequest
	15, // 41: reciprocal_clubs.member.v1.MemberService.GetMemberByUserID:input_type -> reciprocal_clubs.member.v1.GetMemberByUserIDRequest
	16, // 42: reciprocal_clubs.member.v1.MemberService.GetMemberByMemberNumber:input_type -> reciprocal_clubs.member.v1.GetMemberByMemberNumberRequest
	17, // 43: reciprocal_clubs.member.v1.MemberService.GetMembersByClub:input_type -> reciprocal_clubs.member.v1.GetMembersByClubRequest
	19, // 44: reciprocal_clubs.member.v1.MemberService.UpdateMemberProfile:input_type -> reciprocal_clubs.member.v1.UpdateMemberProfileRequest
	22, // 45: reciprocal_clubs.member.v1.MemberService.SuspendMember:input_type -> reciprocal_clubs.member.v1.SuspendMemberRequest
	24, // 46: reciprocal_clubs.member.v1.MemberService.ReactivateMember:input_type -> reciprocal_clubs.member.v1.ReactivateMemberRequest
	26, // 47: reciprocal_clubs.member.v1.MemberService.DeleteMember:input_type -> reciprocal_clubs.member.v1.DeleteMemberRequest
	27, // 48: reciprocal_clubs.member.v1.MemberService.ValidateMemberAccess:input_type -> reciprocal_clubs.member.v1.ValidateMemberAccessRequest
	29, // 49: reciprocal_clubs.member.v1.MemberService.CheckMembershipStatus:input_type -> reciprocal_clubs.member.v1.CheckMembershipStatusRequest
	32, // 50: reciprocal_clubs.member.v1.MemberService.GetMemberAnalytics:input_type -> reciprocal_clubs.member.v1.GetMemberAnalyticsRequest
	39, // 51: reciprocal_clubs.member.v1.MemberService.HealthCheck:input_type -> google.protobuf.Empty
	12, // 52: reciprocal_clubs.member.v1.MemberService.CreateMember:output_type -> reciprocal_clubs.member.v1.CreateMemberResponse
	14, // 53: reciprocal_clubs.member.v1.MemberService.GetMember:output_type -> reciprocal_clubs.member.v1.GetMemberResponse
	14, // 54: reciprocal_clubs.member.v1.MemberService.GetMemberByUserID:output_type -> reciprocal_clubs.member.v1.GetMemberResponse
	14, // 55: reciprocal_clubs.member.v1.MemberService.GetMemberByMemberNumber:output_type -> reciprocal_clubs.member.v1.GetMemberResponse
	18, // 56: reciprocal_clubs.member.v1.MemberService.GetMembersByClub:output_type -> reciprocal_clubs.member.v1.GetMembersByClubResponse
	21, // 57: reciprocal_clubs.member.v1.MemberService.UpdateMemberProfile:output_type -> reciprocal_clubs.member.v1.UpdateMemberProfileResponse
	23, // 58: reciprocal_clubs.member.v1.MemberService.SuspendMember:output_type -> reciprocal_clubs.member.v1.SuspendMemberResponse
	25, // 59: reciprocal_clubs.member.v1.MemberService.ReactivateMember:output_type -> reciprocal_clubs.member.v1.ReactivateMemberResponse
	39, // 60: reciprocal_clubs.member.v1.MemberService.DeleteMember:output_type -> google.protobuf.Empty
	28, // 61: reciprocal_clubs.member.v1.MemberService.ValidateMemberAccess:output_type -> reciprocal_clubs.member.v1.ValidateMemberAccessResponse
	30, // 62: reciprocal_clubs.member.v1.MemberService.CheckMembershipStatus:output_type -> reciprocal_clubs.member.v1.CheckMembershipStatusResponse
	33, // 63: reciprocal_clubs.member.v1.MemberService.GetMemberAnalytics:output_type -> reciprocal_clubs.member.v1.GetMemberAnalyticsResponse
	37, // 64: reciprocal_clubs.member.v1.MemberService.HealthCheck:output_type -> reciprocal_clubs.member.v1.HealthCheckResponse
	52, // [52:65] is the sub-list for method output_type
	39, // [39:52] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_proto_member_proto_init() }
func file_proto_member_proto_init() {
	if File_proto_member_proto != nil {
		return
	}
	file_proto_member_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_member_proto_rawDesc), len(file_proto_member_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_member_proto_goTypes,
		DependencyIndexes: file_proto_member_proto_depIdxs,
		EnumInfos:         file_proto_member_proto_enumTypes,
		MessageInfos:      file_proto_member_proto_msgTypes,
	}.Build()
	File_proto_member_proto = out.File
	file_proto_member_proto_goTypes = nil
	file_proto_member_proto_depIdxs = nil
}
