# =========================================================================
# API Gateway Service - Development Environment
# =========================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-dev
  namespace: reciprocal-clubs-dev
  labels:
    app: api-gateway
    environment: development
    component: gateway
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api-gateway
      environment: development
  template:
    metadata:
      labels:
        app: api-gateway
        environment: development
        component: gateway
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api-gateway
              topologyKey: kubernetes.io/hostname
      containers:
      - name: api-gateway
        image: reciprocal-clubs/api-gateway:dev
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 9080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: GRPC_PORT
          value: "9080"
        - name: METRICS_PORT
          value: "9090"
        envFrom:
        - configMapRef:
            name: reciprocal-clubs-dev-config
        - secretRef:
            name: reciprocal-clubs-dev-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: reciprocal-clubs-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-dev-service
  namespace: reciprocal-clubs-dev
  labels:
    app: api-gateway
    environment: development
    component: gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9080
    targetPort: 9080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: api-gateway
    environment: development

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-dev-monitor
  namespace: reciprocal-clubs-dev
  labels:
    app: api-gateway
    environment: development
    component: gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
      environment: development
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-dev-hpa
  namespace: reciprocal-clubs-dev
  labels:
    app: api-gateway
    environment: development
    component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-dev
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-dev-pdb
  namespace: reciprocal-clubs-dev
  labels:
    app: api-gateway
    environment: development
    component: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
      environment: development